version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "yearly"
    groups:
      gradle:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "yearly"
    groups:
      github-actions:
        patterns:
          - "*"
